link1: "https://screencasts.railstutorial.org/"
link2: "https://www.railstutorial.org/book"
link3: "https://www.learnenough.com/"
link4: "https://www.learnenough.com/"
link5: "https://rubyonrails.org/"
link6: "https://www.railstutorial.org/"
link7: "https://www.railstutorial.org/contact"
link8: "https://www.railstutorial.org/help"
link9: "https://www.railstutorial.org/book"
